import {Hero,PageHero} from './components/hero.mjs';
import {HomeIntro} from './components/home-intro.mjs';
import {HomeServices} from './components/home-services.mjs';
import {HomeMethodology} from './components/home-methodology.mjs';
import {HomeContinuity} from './components/home-continuity.mjs';
import {HomeInsights} from './components/home-insights.mjs';
import {ServiceNavigation,RelatedServices} from './components/services.mjs';
import {Methodology} from './components/methodology.mjs';
import {Industries} from './components/industries.mjs';
import {ContactCTA} from './components/cta.mjs';
import {ContactForm} from './components/form.mjs';
import {services,sectors} from './content.mjs';
import {url,cta,arrow} from './config.mjs';

export const pages = [
 {path:'',title:'Protegemos la continuidad de tu operación',description:'Consultoría en prevención, investigación corporativa, administración de riesgos, capacitación y consultoría legal. Propuesta de sitio Biding México.',body:Hero()+HomeIntro()+HomeServices()+HomeMethodology()+Industries()+HomeContinuity()+HomeInsights()+ContactCTA()},
 {path:'nosotros/',active:'nosotros',title:'Nosotros: una perspectiva integral del riesgo',description:'Conoce el enfoque multidisciplinario de Biding México: prevención, análisis y continuidad operativa con confianza, honestidad y respeto.',body:PageHero('Nosotros','La prevención es<br> una forma de pensar.','Entender cómo funciona una organización es el primer paso para ayudarla a seguir adelante.')+`<section class="wrap about-story section"><div><h2>Una mirada integral.<br> Decisiones con contexto.</h2><p class="lead">Los riesgos no respetan los límites entre áreas. Nuestro enfoque tampoco.</p><p>Biding México reúne especialidades de investigación, prevención, administración de riesgos, capacitación y consultoría legal. Esta perspectiva permite relacionar lo que ocurre en campo con los procesos y decisiones de la organización.</p><p>El punto de partida es escuchar, revisar el contexto y comprender la exposición. A partir de ahí, la prevención se convierte en medidas concretas para las personas, los activos y la continuidad operativa.</p></div><img src="${url('assets/logistics.webp')}" alt="Instalación logística como contexto de la gestión de riesgos" width="1400" height="933" loading="lazy"></section><section class="section values"><div class="wrap"><h2>La confianza también<br> se construye en la forma de trabajar.</h2><div class="values-grid"><div><span>01</span><h3>Confianza</h3><p>Escuchar el contexto y cuidar la información para construir relaciones profesionales claras.</p></div><div><span>02</span><h3>Honestidad</h3><p>Hablar con claridad sobre los hallazgos, los alcances y los límites de cada intervención.</p></div><div><span>03</span><h3>Respeto</h3><p>Reconocer a las personas, sus responsabilidades y las condiciones de cada organización.</p></div></div></div></section><section class="section wrap editorial-note"><h2>Una historia por contar con precisión.</h2><p>En la versión final, este espacio integrará la trayectoria, el equipo directivo y las acreditaciones que Biding México proporcione y valide.</p><span class="status-label">Contenido corporativo pendiente de validación</span></section>`+Methodology()+ContactCTA()},
 {path:'servicios/',active:'servicios',title:'Servicios de gestión integral de riesgos',description:'Cinco especialidades conectadas: prevención y seguridad, investigación corporativa, administración de riesgos, capacitación y consultoría legal.',body:PageHero('Servicios','Distintas especialidades.<br> La misma visión preventiva.','Una perspectiva multidisciplinaria para entender la exposición de tu organización y definir cómo actuar.')+ServiceNavigation({full:true})+Methodology()+ContactCTA()},
 {path:'sectores/',active:'sectores',title:'Sectores: transporte, logística, seguros e industria',description:'Prevención y gestión de riesgos aplicada a transporte, logística, sector asegurador, industria, empresas e instituciones.',body:PageHero('Sectores','El contexto cambia.<br> El compromiso de prevenir, no.','Cada operación tiene sus propias condiciones. Por eso, el análisis comienza en la realidad de cada sector.')+Industries()+ContactCTA()},
 {path:'insights/',active:'insights',title:'Insights: prevención y continuidad de negocio',description:'Espacio editorial propuesto para análisis sobre seguridad logística, prevención de pérdidas y continuidad de negocio.',body:PageHero('Insights','Entender mejor.<br> Decidir con más claridad.','Perspectivas sobre prevención, seguridad logística y continuidad de negocio.')+`<section class="wrap section insight-empty"><span class="status-label">Contenidos en preparación</span><h2>Una agenda de conocimiento<br> conectada con la operación.</h2><p>Este espacio está preparado para publicar artículos, guías e informes validados por Biding México. La propuesta contempla las siguientes líneas editoriales:</p><div class="topic-grid"><article><span>Transporte y logística</span><h3>Seguridad en cada trayecto</h3><p>Análisis de rutas, manejo defensivo y prevención de incidentes en la cadena logística.</p></article><article><span>Gestión de riesgos</span><h3>Comprender la exposición</h3><p>Fuentes de pérdida, auditorías y relación entre prevención y programas de seguros.</p></article><article><span>Continuidad</span><h3>Preparar a la organización</h3><p>Procesos, capacitación y decisiones que contribuyen a proteger la operación.</p></article></div></section>`+ContactCTA()},
 {path:'contacto/',active:'contacto',title:'Contacto: hablemos sobre tu operación',description:'Explora una solicitud de evaluación de riesgos para tu empresa. Formulario demostrativo, sin envío de información.',body:PageHero('Contacto','Toda prevención comienza<br> con una conversación.','Identifiquemos qué necesitas proteger y qué puntos de tu operación merecen atención.')+ContactForm()}
];
services.forEach((s,i)=>pages.push({path:'servicios/'+s.slug+'/',active:'servicios',title:s.name,description:s.description,body:PageHero('Servicios / '+s.name,s.name,s.description)+`<section class="wrap section detail-intro"><div><p class="eyebrow">El contexto</p><h2>${s.context}</h2></div><p class="lead">${s.body}</p></section><section class="capabilities section"><div class="wrap"><p class="eyebrow">Alcance de la especialidad</p><h2>Capacidades para<br> entender y atender el riesgo.</h2><ul class="capability-grid">${s.capabilities.map((c,j)=>`<li><span>0${j+1}</span><h3>${c}</h3></li>`).join('')}</ul></div></section><section class="wrap section detail-intro"><div><h2>Aplicación en la operación.</h2><p>${s.use}</p></div><div><h3>Definimos el alcance contigo</h3><p>${s.output}</p>${cta('Solicitar información','',s.slug)}</div></section>`+Methodology()+RelatedServices([0,1,2,3,4].filter(n=>n!==i).slice(0,3))+ContactCTA(s.question,s.slug)}));
sectors.forEach(s=>pages.push({path:'sectores/'+s.slug+'/',active:'sectores',title:'Gestión de riesgos para '+s.name.toLowerCase(),description:s.text+' '+s.body,body:PageHero('Sectores / '+s.name,s.name,s.text)+`<section class="wrap section detail-intro"><h2>Prevenir desde<br> el contexto real.</h2><p class="lead">${s.body}</p></section><section class="section capabilities"><div class="wrap"><h2>Puntos de atención</h2><ul class="capability-grid">${s.needs.map((n,i)=>`<li><span>0${i+1}</span><h3>${n}</h3></li>`).join('')}</ul></div></section>`+RelatedServices(s.related,'Especialidades que se conectan con tu sector.')+ContactCTA()}));
